# Generated by Django 5.1.6 on 2025-07-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
